version: '3'
name: docker-studing

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    hostname: frontend
    restart: always

    ports:
      - "5173:5173"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: always
    hostname: backend
    volumes:
      - ./backend/app:/code/app
    ports:
      - "8000:8000"
